lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_10/urls.py
from django.conf.urls import url
from .views import *

from lab_9.custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/$', dashboard, name='dashboard'),

    #movie
    url(r'^movie/list/$', movie_list, name='movie_list'),
    url(r'^movie/detail/(?P<id>.*)/$', movie_detail, name='movie_detail'),

    # Session dan Model (Watch Later)
    url(r'^movie/watch_later/add/(?P<id>.*)/$', add_watch_later, name='add_watch_later'),
    url(r'^movie/watch_later/$', list_watch_later, name='list_watch_later'),

    #API
    url(r'^api/movie/(?P<judul>.*)/(?P<tahun>.*)/$', api_search_movie, name='api_search_movie'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url="/lab-4/",permanent="true"), name='index'),

]

lab_10/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class MovieKu(models.Model):
    pengguna = models.ForeignKey(Pengguna)
    kode_movie = models.CharField("Kode Movie", max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

lab_10/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .omdb_api import get_detail_movie, search_movie
from .utils import *
response = {}

# Create your views here.

### USER
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('lab-10:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        response['connected'] = False #digunakan sebagai penanda kapan header menampilkan tombol logout
        response['name'] = 'Samuel Tupa Febrian'
        html = 'lab_9/session/login.html'
        return render(request, html, response)

def dashboard(request):
    print ("#==> dashboard")

    if not 'user_login' in request.session.keys():
        return HttpResponseRedirect(reverse('lab-10:index'))
    else:
        set_data_for_session(request)
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)

        movies_id = get_my_movies_from_session(request)
        save_movies_to_database(pengguna, movies_id)
        response['access_token'] = request.session['access_token']
        response['kode_identitas'] = request.session['kode_identitas']
        response['connected'] = True
        html = 'lab_10/dashboard.html'
        return render(request, html, response)

### MOVIE : LIST and DETAIL
def movie_list(request):
    judul, tahun = get_parameter_request(request)
    urlDataTables = "/lab-10/api/movie/" + judul + "/" + tahun
    jsonUrlDT = json.dumps(urlDataTables)
    response['jsonUrlDT'] = jsonUrlDT
    response['judul'] = judul
    response['tahun'] = tahun
    get_data_session(request)
    html = 'lab_10/list.html'
    return render(request, html, response)

def movie_detail(request, id):
    print ("MOVIE DETAIL = ", id)
    response['id'] = id
    if get_data_user(request, 'user_login'):
        is_added = check_movie_in_database(request, id)
    else:
        is_added = check_movie_in_session(request, id)

    response['added'] = is_added
    response['movie'] = get_detail_movie(id)
    html = 'lab_10/detail.html'
    return render(request, html, response)

### WATCH LATER : ADD and LIST
def add_watch_later(request, id):
    print ("ADD WL => ", id)
    msg = "Berhasil tambah movie ke Watch Later"
    check_exist = get_detail_movie(id)
    if str(check_exist["response"])=="b'True'" :
        if get_data_user(request, 'user_login'):

            print ("TO DB")
            is_in_db = check_movie_in_database(request, id)
            if not is_in_db:
                add_item_to_database(request, id)
            else:
                msg = "Movie already exist on DATABASE! Hacking detected!"
        else:
            print ("TO SESSION")
            is_in_ssn = check_movie_in_session(request, id)
            if not is_in_ssn:
                add_item_to_session(request, id)
            else:
                msg = "Movie already exist on SESSION! Hacking detected!"
    else:
        msg = "Movie tidak dapat ditambahkan : id tidak ditemukan"
        messages.error(request, msg)
        return HttpResponseRedirect(reverse('lab-10:index'))
    messages.success(request, msg)
    return HttpResponseRedirect(reverse('lab-10:movie_detail', args=(id,)))

def list_watch_later(request):
    #  Implement this function by yourself
    get_data_session(request)
    moviesku = []
    if get_data_user(request, 'user_login'):
        moviesku = get_my_movies_from_database(request)
    else:
        moviesku = get_my_movies_from_session(request)

    watch_later_movies = get_list_movie_from_api(moviesku)
    response['watch_later_movies'] = watch_later_movies
    html = 'lab_10/watch_later.html'
    return render(request, html, response)

### SESSION : GET and SET
def get_data_session(request):
    if get_data_user(request, 'user_login'):
        response['author'] = get_data_user(request, 'user_login')

def set_data_for_session(request):
    response['author'] = get_data_user(request, 'user_login')
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

### API : SEARCH movie
def api_search_movie(request, judul, tahun):
    print ("API SEARCH MOVIE")
    if judul == "-" and tahun == "-":
        items = []
    else:
        search_results = search_movie(judul, tahun)
        items = search_results

    dataJson = json.dumps({"dataku":items})
    mimetype = 'application/json'
    return HttpResponse(dataJson, mimetype)

lab_10/templates/lab_10/dashboard.html
{% extends "lab_10/layout/base.html" %}

{% block content %}
<!-- Content Here -->
<section id="data-dashboard">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2> Dashboard </h2>
        </div>
        <div class="panel-body">
            <p> Username : {{ author }} </p>
            <p> NPM : {{kode_identitas}} </p>
            <p> Role : {{ role }} </p>
            <p>
                <a href="{% url 'lab-10:movie_list' %}" class="btn btn-primary"> Daftar Movie </a> |
                <a href="{% url 'lab-10:list_watch_later' %}" class="btn btn-warning"> Daftar Watch Later </a>
            </p>
        </div>
        <div class="panel-footer">
            <a href="{% url 'lab-10:auth_logout' %}" class="btn btn-danger" onclick="return confirm('Keluar?')">
                Logout </a>
        </div>
    </div>
</section>
<hr>

{% endblock %}

lab_10/templates/lab_10/detail.html
{% extends "lab_10/layout/base.html" %}

{% block content %}
<div class="box">
    {% if added %}
    <button class="btn btn-success"> Added to Watch Later </button>
    {% else %}
    <a href="{% url 'lab-10:add_watch_later' id %}" class="btn btn-warning"> Add to Watch Later </a>
    {% endif%}
</div>
<br>
<div class="panel panel-info">
    <div class="panel-heading">
        <h1 style="text-align: center;"> {{movie.title}} </h1>
    </div>
<div class="panel-body w3-theme-l5">
    {% if movie.poster|stringformat:"s" == "b'N/A'" %}
        <img style="margin: 0px auto;display:block;" src="https://i5.walmartimages.com/asr/f752abb3-1b49-4f99-b68a-7c4d77b45b40_1.39d6c524f6033c7c58bd073db1b99786.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF"/>
    {% else %}
        <img style="margin: 0px auto;display:block;" src="{{movie.poster}}"/>
    {% endif %}
    <br>
    <p style="text-align: center;font-size: 20px" >{{movie.plot}}<p>
    <br>
    <h2>Details : </h2>
    <hr/>
<table style="width:100%">
  <tr>
    <td><b>Title</b></td>
    <td>{{movie.title}}</td>
  </tr>
  <tr>
    <td><b>Year</b></td>
    <td>{{movie.year}}</td>
  </tr>
  <tr>
    <td><b>Rated</b></td>
    <td>{{movie.rated}}</td>
  </tr>
  <tr>
    <td><b>Released Date</b></td>
    <td>{{movie.released}}</td>
  </tr>
  <tr>
    <td><b>Duration</b></td>
    <td>{{movie.runtime}}</td>
  </tr>
  <tr>
    <td><b>Genre</b></td>
    <td>{{movie.genre}}</td>
  </tr>
  <tr>
    <td><b>Director</b></td>
    <td>{{movie.director}}</td>
  </tr>
  <tr>
    <td><b>Writer</b></td>
    <td>{{movie.writer}}</td>
  </tr>
  <tr>
    <td><b>Actors</b></td>
    <td>{{movie.actors}}</td>
  </tr>
  <tr>
    <td><b>Language</b></td>
    <td>{{movie.language}}</td>
  </tr>
  <tr>
    <td><b>Country</b></td>
    <td>{{movie.country}}</td>
  </tr>
  <tr>
    <td><b>Awards</b></td>
    <td>{{movie.awards}}</td>
  </tr>
  <tr>
    <td><b>Rating:</b><br>
        {% for sc in movie.ratings %}
            <b>{{sc.Source}}<b><br>
        {% endfor %}
    </td>
    <td><br>
        {% for sc in movie.ratings %}
            {{sc.Value}}<br>
        {% endfor %}
    </td>
  </tr>
  <tr>
    <td><b>Metascore</b></td>
    <td>{{movie.metascore}}</td>
  </tr>
  <tr>
    <td><b>IMDb Rating</b></td>
    <td>{{movie.imdbrating}}</td>
  </tr>
  <tr>
    <td><b>IMDb Votes</b></td>
    <td>{{movie.imdbvotes}}</td>
  </tr>
  <tr>
    <td><b>DVD Release</b></td>
    <td>{{movie.dvd}}</td>
  </tr>
  <tr>
    <td><b>Box Office</b></td>
    <td>{{movie.boxoffice}}</td>
  </tr>
  <tr>
    <td><b>Production</b></td>
    <td>{{movie.production}}</td>
  </tr>
  <tr>
    <td><b>Website</b></td>
    <td>
        {% if movie.website|stringformat:"s" == "b'N/A'" %}
            <p>N/A</p>
        {% else %}
            <a href="{{movie.website}}">{{movie.website}}</a>
        {% endif %}
        
    </td>
  </tr>
</table>
</div>
</div>

{% endblock %}

lab_10/templates/lab_10/list.html
{% extends "lab_10/layout/base.html" %}

{% block content %}
<!-- User Login Here -->
{% if user_login %}
<a href="" class="btn btn-primary btn-lg"> Logout </a>

{% else %}
<p>
    <a href="{% url 'lab-10:list_watch_later' %}" class="btn btn-primary btn-lg "> Daftar <em>Watch Later </em> </a>
</p>

{% endif %}
<br>
<!-- List Movie -->
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> List Movie </h2>
    </div>
    <div class="panel-body">
        <div style="margin:20px; padding:20px; background-color:lightsteelblue; border-radius:3px;">
            <form method="GET" action="{% url 'lab-10:movie_list' %}" class="form-inline">
                <label> Nama </label> <input type="text" class="form-control" name="judul" placeholder="Judul"
                                             value="{{judul}}">
                <label> Tahun </label> <input type="text" class="form-control" name="tahun" placeholder="Tahun "
                                              value="{{tahun}}">
                <input type="submit" class="btn btn-primary pull-right">
            </form>
        </div>
        <hr>
        <div class="table table-responsive">
            <table class="table table-hover" id="myTable" style="width: none;">
                <thead>
                <th> Judul</th>
                <th> Tahun</th>
                <th> Poster</th>
                <th> Detail</th>
                </thead>
            </table>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function(e) {
        $('#myTable').DataTable( {
            "ajax": {
                "dataType" : 'json',
                "contentType": "application/json; charset=utf-8",
                "url": {% autoescape off %} {{ jsonUrlDT }} {% endautoescape%} ,
                "dataSrc":"dataku",
            },
            "columns" : [
                {"data" : "Title"},
                {"data" : "Year"},
                {
                    "data" : "Poster",
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        if(oData.Poster == "N/A"){
                            $(nTd).html("<img src='"+ 'https://i5.walmartimages.com/asr/f752abb3-1b49-4f99-b68a-7c4d77b45b40_1.39d6c524f6033c7c58bd073db1b99786.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF' +"' style='height:50%' class='img-responsive img-thumbnail'/>");
                        }else{
                            $(nTd).html("<img src='"+ oData.Poster +"' style='height:50%' class='img-responsive img-thumbnail'/>");
                        }
                    }
                },
                {
                    "data" : null,
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        $(nTd).html("<a href='/lab-10/movie/detail/"+ oData.imdbID +"' class='btn btn-primary'> Detail </a>");
                    }
                }
            ],
        } );
    });
</script>

{% endblock %}

lab_10/templates/lab_10/watch_later.html
{% extends "lab_10/layout/base.html" %}

{% block content %}

<!-- List Movie -->
<div class="panel panel-info">
    <div class="panel-heading" style="text-align: center">
        <h2> List Movie for Watch Later </h2>
    </div>
    <div class="panel-body">
            <table class="table table-hover" id="myTable" style="width: none;">
                <thead>
                <tr>
                <th style="text-align: center"> Judul</th>
                <th style="text-align: center"> Poster</th>
                <th style="text-align: center"> Detail</th>
            	</tr>
                </thead>
                <tbody>
                	{% for movie in watch_later_movies %}
                	<tr>
                		<td>{{movie.title}}</td>
                		<td>
                			{% if movie.poster|stringformat:"s" == "b'N/A'" %}
                			<img style="margin: 0px auto;display:block;" src="https://i5.walmartimages.com/asr/f752abb3-1b49-4f99-b68a-7c4d77b45b40_1.39d6c524f6033c7c58bd073db1b99786.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF"/>
                			{% else %}
                			<img style="margin: 0px auto;display:block;" src="{{movie.poster}}"/>
                			{% endif %} 
                		</td>
                		<td style="text-align: center"><a href='/lab-10/movie/detail/{{movie.imdbid}}' class='btn btn-primary'> Detail </a></td>
                	</tr>
                	{% endfor %}
                </tbody>
            </table>
    </div>
</div>
{% endblock %}