lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, validate_npm, delete_friend, friend_list, add_friend, get_friend_list, get_list_at_page

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    url(r'^friend-list/$', friend_list, name='friend-list'),
    url(r'^get-friend-list/$', get_friend_list, name='get-friend-list'),
    url(r'^change-page/$', get_list_at_page, name='change-page'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url="/lab-4/",permanent="true"), name='index'),

]

lab_7/models.py
from django.db import models


class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
    page = request.GET.get('page', 1)
    resp = csui_helper.instance.get_mahasiswa_list(page)
    mahasiswa_list = resp['results']
    friend_list = Friend.objects.all()
    response = {"author":"Samuel Tupa Febrian","current_page": page, "mahasiswa_list": mahasiswa_list, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

@csrf_exempt
def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar-teman.html'
    return render(request, html, response)

@csrf_exempt
def get_friend_list(request):
    return JsonResponse(dict(friend_list=list(Friend.objects.values())))

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        is_taken = Friend.objects.filter(npm__iexact=npm).exists()
        if not is_taken:
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
    status = False
    if request.method == 'POST':
        friend_id = request.POST['id']
        Friend.objects.filter(id=friend_id).delete()
        status = True
    return JsonResponse({'status':status})


@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm__iexact=npm).exists() #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

@csrf_exempt
def get_list_at_page(request):
    if request.method == 'POST':
        page = request.POST['page']
        listAtPage = csui_helper.instance.get_mahasiswa_list(page)['results']
        return JsonResponse({'listOfMhs': json.dumps(listAtPage)})

lab_7/templates/lab_7/daftar-teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        var emptyAlert = function(lengthData) {
            if (lengthData == 0){
                $(".container").append('<div class="alert alert-danger text-center"><strong>Oops!</strong> Tidak ada mahasiswa</div>');
            }
        };

		var deletefriend = function(id) {

			$.ajax({
            method: "POST",
            url: "{% url "lab-7:delete-friend" %}",
            data: {id:id},
            success : function (status) {
                $("#friend-" + id).remove();
                emptyAlert($("#friend-list").children().length - 1);
            },
            error : function (error) {
				alert("Penghapusan teman gagal");
            }
			});
			};

        $( document ).ready(function () {

            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
				url: "{% url "lab-7:get-friend-list" %}",
                success: function (response) {
				lst = response.friend_list;
                emptyAlert(lst.length);
				for (fr in lst) {
					html = '<a class="list-group-item clearfix" id=' + 'friend-' + lst[fr].id +'>' +
					    lst[fr].friend_name + " " + lst[fr].npm;
					html += '<span class="pull-right">'
						+ '<span class="btn btn-xs btn-default" onClick="deletefriend('
					    + "'" + lst[fr].id + "')" + '">'
					    + "Hapus</span></span></a>";
					$("#friend-list").append(html);
                }},
                error: function(error){
					alert("Data tidak dapat dimasukkan");
                }
            });
        });

    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <span class="btn btn-xs btn-default pagination-btn" onClick="prevPage()">Prev</span>
                <span class="btn btn-xs btn-default pagination-btn" onClick="nextPage()">Next</span>
                <div class="list-group" id="mahasiswa-all-list">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center" id="no-friend">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    var page = {{ current_page }};
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
				objFr = JSON.parse(friend);
                html = '<a class="list-group-item clearfix">' +
                    objFr.friend_name + ' (' + objFr.npm + ")" +
                    '</a>';
                $("#friend-list").append(html);
                if ($("#no-friend").length > 0) {
                    $("#no-friend").remove();
                    }
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });

    };
    var prevPage = function() {
        page--;
        changePage(page);
    };

    var nextPage = function() {
        page++;
        changePage(page);
    };

    var changePage = function(page) {
    $.ajax({
        method: "POST",
        url: '{% url "lab-7:change-page" %}',
        data: {'page': page},
        dataType: 'json',
        success: function (response) {
            $("#mahasiswa-all-list").empty();
            window.history.pushState("", "LAB TUJUH", '{% url "lab-7:index" %}' + '?page=' + page);

            listOfMhs = JSON.parse(response.listOfMhs);
            for (mhs in listOfMhs) {
                m = listOfMhs[mhs];
                html = '<a class="list-group-item clearfix">' +
                    m.nama + ' (' + m.npm + ')<span class="pull-right">'
                    +'<span class="btn btn-s btn-default" onClick="addFriend(' +
                    "'" + m.nama + "', '" + m.npm + "'" + ')">Tambah sebagai teman</span></span></a>';
                $("#mahasiswa-all-list").append(html);
            }
        },
    });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val();
       npm = $("#field_npm").val();
        addFriend(name, npm);
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data);
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}